### PR TITLE
Replacing the iw command with hostapd_cli to get active ssid name

### PR DESCRIPTION
**Pull request by Rajakumaran1106**
Signed-off-by: Rajakumaran1106 <rajakumaran.a@ltts.com>

### CODE REVIEW

**Comment by mhughesacn** [comment]
Hi Rajakumaran.  Long story, but the blackduck error is because of a pre-existing compliance issue with this file.  There is an open ticket, so I can approve but if you have the time, it would be really helpful if you could make the necessary changes as a part of this pull request:

1. In source/wifi/wifi_hal.c, at the top of file after the Apache header, add a comment saying:
"Material from the TR181 data model is Copyright (c) 2010-2017, Broadband Forum
Licensed under the BSD-3 license"

2. Append the same two lines to NOTICE at the top level.

Many thanks,
Martin Hughes, (RDK CMF Compliance Team)

**Comment by Rajakumaran1106** [comment]
> Hi Rajakumaran. Long story, but the blackduck error is because of a pre-existing compliance issue with this file. There is an open ticket, so I can approve but if you have the time, it would be really helpful if you could make the necessary changes as a part of this pull request:
> 
> 1. In source/wifi/wifi_hal.c, at the top of file after the Apache header, add a comment saying:
>    "Material from the TR181 data model is Copyright (c) 2010-2017, Broadband Forum
>    Licensed under the BSD-3 license"
> 2. Append the same two lines to NOTICE at the top level.
> 
> Many thanks,
> Martin Hughes, (RDK CMF Compliance Team)

**Comment by Rajakumaran1106** [comment]
Hi Martin , I have added the License as suggested

**Comment by mhughesacn** [comment]
Hi Rajakumaran, Thanks for doing this.

**Comment by manigandanj** [comment]
Looks good to me.

**Review by rajkumar154 — APPROVED** [review]

**Pull request merged**
